--- 
name: 'Products'
settings: 
  - 
    type: 'text'
    id: 'title'
    label: 'Title'
  - 
    type: 'textarea'
    id: 'subtitle'
    label: 'Subtitle'
  - 
    type: 'colorpicker'
    id: 'text_color'
    label: 'Text Color'
  - 
    type: 'select'
    id: 'background'
    label: 
      -
        value: 'blue'
        label: 'Blue'
      -
        value: 'light_grey'
        label: 'Light Grey'
      -
        value: 'black'
        label: 'black'
        